hypv-intercept: Fix conflict in header files
There is a conflict between android utils/Log.h and syslog.h in
the g++ 5.3.0, which will cause the following compilation error.
"error: macro "LOG_PRI" passed 5 arguments, but takes just 1"

Change-Id: I85d5e462e6527da5ebbef138cf534cc370b7fb49
Signed-off-by: Miaomiao Chen <miaochen@codeaurora.org>